$(document).ready(function(){
    $("div.show").click(function(){
        $("#design").show();
        $("div.show").hide();
    });
    $("div.show1").click(function(){
        $("#development").show();
        $("div.show1").hide();
    });
    $("div.show2").click(function(){
        $("#product").show();
        $("div.show2").hide();
    });
});
$(document).ready(function(){
    $("#design").click(function(){
        $("div.show").show();
        $("#design").hide();
    });
    $("#development").click(function(){
        $("div.show1").show();
        $("#development").hide();
    });
    $("#product").click(function(){
        $("div.show2").show();
        $("#product").hide();
    });
});
$(document).ready(function(){
    $(".wrap1").mouseover(function(){
        $("#overlay1").show();
    }).mouseout(function(){
        $("#overlay1").hide();
    });
});
$(document).ready(function(){
    $(".wrap2").mouseover(function(){
        $("#overlay2").show();
    }).mouseout(function(){
        $("#overlay2").hide();
    });
});
$(document).ready(function(){
    $(".wrap3").mouseover(function(){
        $("#overlay3").show();
    }).mouseout(function(){
        $("#overlay3").hide();
    });
});
$(document).ready(function(){
    $(".wrap4").mouseover(function(){
        $("#overlay4").show();
    }).mouseout(function(){
        $("#overlay4").hide();
    });
});
$(document).ready(function(){
    $(".wrap5").mouseover(function(){
        $("#overlay5").show();
    }).mouseout(function(){
        $("#overlay5").hide();
    });
});
$(document).ready(function(){
    $(".wrap6").mouseover(function(){
        $("#overlay6").show();
    }).mouseout(function(){
        $("#overlay6").hide();
    });
});
$(document).ready(function(){
    $(".wrap7").mouseover(function(){
        $("#overlay7").show();
    }).mouseout(function(){
        $("#overlay7").hide();
    });
});
$(document).ready(function(){
    $(".wrap8").mouseover(function(){
        $("#overlay8").show();
    }).mouseout(function(){
        $("#overlay8").hide();
    });
});

used variable name for all  
$(document).ready(function(){
    $("form").submit(function(){
        var name = $("textarea#textarea").val();
        var name = $("input#email").val();
        var name = $("input#name").val();
        if($("input#name").val() && $("input#email").val() && $("textarea#textarea").val() !=""){
            alert(name+" we have received your message.Thankyou for contacting us!!");
        }
        else
        {
            alert("please enter your name,email and message.")
        }
    });
});
